### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by ColorTwist** [Zastai/MetaBrainz.ListenBrainz#1]
Very nice addon to c# for ListenBrainz!
Do you have example of usage for this API?
There is non in the readme or the project.

**Comment by Zastai** [comment]
That's a good point, I'll look at either adding some to the README or in the IntelliSense comments.

Short version:
* you can set a few defaults statically on the `ListenBrainz` objects
* you create a new `ListenBrainz` instance
  * this requires setting a valid user agent (used by the LB site for rate limiting); there's a few constructor forms to help with that
* you call methods corresponding to the LB web API endpoints (async or non-async)
  * only one endpoint has been added so far
* rate limiting should be handled automatically by the library based on info returned by LB

So:
```c#
var lb = new ListenBrainz("test", "1.0", "mailto:name@domain.com");
var li = lb.LatestImport("theUser");
// rate limit info should be available in lb.RateLimitInfo at this point
Console.WriteLine($"Latest import by user {li.User} was on {li.Timestamp}.");
```

**Comment by ColorTwist** [comment]
Yeah, samples would be helpful here :) thanks!

Where can i see which members are returned to the `li` object?

**Comment by Zastai** [comment]
IntelliSense should tell you that. The `LatestImport` method returns an `ILatestImport` interface; these are all in the Interfaces namespace.

**Comment by ColorTwist** [comment]
I see, i checked it out. 
Actually, i am sure i understand what this API can be used for if i can only get User name and latest import date.
I thought i can get the some actual data like which tracks/artists were listened to by the user.

**Comment by Zastai** [comment]
It was just the first API endpoint I hooked up. The MusicBrainz project does have the full API, this one is just starting. I don't use LB myself, so I haven't really had much reason to do much work on it.

**Comment by Zastai** [comment]
Just noting that this is now at 1.0 release, and has the full set of current endpoints.
Documentation is still limited to IntelliSense for now.
